spring:
  application:
    name: BiddingSystem

  datasource:
    url: jdbc:postgresql://localhost:5432/newdb
    username: postgres
    password: dsa

  jpa:
    hibernate:
      ddl-auto: create-drop   # Hibernate will create/update your tables
    show-sql: true
    defer-datasource-initialization: true

jwt:
  secret: "ODE2YzBhNmJlMmFkODcxYzM5YWIwNjc5ZTM1Mzc5ZTY0ODc2Y2ZkMzg0MmQwZmEzZTgwYjliM2I="
  message: "Your message or custom token message"

  sql:
    init:
      mode: always
